//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by GitVersion.
//
// You can modify this code as we will not overwrite it when re-executing GitVersion
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

[assembly: AssemblyFileVersion("0.2.0.0")]
[assembly: AssemblyVersion("0.2.0.28")]
[assembly: AssemblyInformationalVersion("0.2.0-alpha.28+Branch.develop.Sha.ad63e99c977ffc985b090ef612bff26fd6766cd6")]
