//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by GitVersion.
//
// You can modify this code as we will not overwrite it when re-executing GitVersion
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

[assembly: AssemblyFileVersion("0.2.0.0")]
[assembly: AssemblyVersion("0.2.0.26")]
[assembly: AssemblyInformationalVersion("0.2.0-alpha.26+Branch.develop.Sha.e27c78867f1a54ad8188cefbfa3cbcc3b9db14f8")]
